

-- # Entity Integrity checks


SELECT 
    'Total rows stg_mtk_campaign' AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM DXLINEA_INTERVIEW.RAW_DXLINEA.STG_MKT_CAMPAIGN

UNION ALL 


SELECT 
    'Distinct primary key CAMPAIGN_ID' AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM (SELECT DISTINCT CAMPAIGN_ID FROM  DXLINEA_INTERVIEW.RAW_DXLINEA.STG_MKT_CAMPAIGN WHERE CAMPAIGN_ID IS NOT NULL ) ;

-- Result: Within mkt_campaign, each row is unique, non-null, and represents exactly one campaign.


SELECT 
    'Total rows STG_MKT_LEAD' AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM DXLINEA_INTERVIEW.RAW_DXLINEA.STG_MKT_LEAD

UNION ALL 


SELECT 
    'Distinct primary key LEAD_ID'  AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM (SELECT DISTINCT LEAD_ID FROM  DXLINEA_INTERVIEW.RAW_DXLINEA.STG_MKT_LEAD WHERE LEAD_ID IS NOT NULL ) ;

-- Result: Within STG_MKT_LEAD, each row is unique, non-null, and represents exactly one lead.


SELECT 
    'Total rows STG_SFDC_OPPORTUNITY' AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM DXLINEA_INTERVIEW.RAW_DXLINEA.STG_SFDC_OPPORTUNITY


UNION ALL 


SELECT 
    'Distinct primary key OPPORTUNITY_ID'  AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM (SELECT DISTINCT OPPORTUNITY_ID FROM  DXLINEA_INTERVIEW.RAW_DXLINEA.STG_SFDC_OPPORTUNITY WHERE OPPORTUNITY_ID IS NOT NULL ) ;
-- Result: Within STG_MKT_LEAD, each row is unique, non-null, and represents exactly one opportunity.


SELECT 
    'Total rows STG_SFDC_ACCOUNT' AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM DXLINEA_INTERVIEW.RAW_DXLINEA.STG_SFDC_ACCOUNT


UNION ALL 


SELECT 
    'Distinct primary key ACCOUNT_ID'  AS METRIC_NAME
    ,COUNT(*) AS METRIC_VALUE
FROM (SELECT DISTINCT ACCOUNT_ID FROM  DXLINEA_INTERVIEW.RAW_DXLINEA.STG_SFDC_ACCOUNT WHERE ACCOUNT_ID IS NOT NULL ) ;
-- Result: Within STG_MKT_LEAD, each row is unique, non-null, and represents exactly one account.





